# Site settings
title: "树林林的小空间"
subtitle: "hello world"
email: "jingyu3hao@gmail.com"
description: "我就是我啊"
baseurl: "/site/"
url: "http://blueskey.github.io" 
twitter_username: "liuju"
github_username:  "blueskey"
instagram_username: "rowanoulton"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
