# Site settings
title: 面朝大海，春暖花开
email: jingyu3hao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    树林林的小空间
    独怜忧草涧边生，上有黄鹂深树鸣
baseurl: "/site/" # our awesome titlethe subpath of your site, e.g. /blog/
url: "http://blueskey.github.io" # the base hostname & protocol for your site
twitter_username: liuju
github_username:  blueskey

# Build settings
markdown: kramdown
