# Site settings
title: "兴来每独往，胜事空自知。行到水穷处，坐看云起时"
subtitle: "hello world"
email: "jingyu3hao@gmail.com"
description: "我就是我啊"
baseurl: "/site"
url: "http://blueskey.github.io" 
#url: "http://localhost:4000"

twitter_username: "liuju"
github_username:  "blueskey"
instagram_username: "rowanoulton"

#highlighter: pygemnts
highlighter: rouge

#encoding: utf-8

#pygments: true

# Build settings
markdown: kramdown

permalink: pretty

# Pagination
gems: [jekyll-paginate]
paginate: 5

# Sass
sass:
    style: :compressed
